### ISSUE TITLE
Doesn't Work on Neoload 9.0

### ISSUE THREAD

**Issue by CamilleGR** [Neotys-Labs/AppDynamics#7]
The plugin doesn't work on Neoload 9.0. Check VU give the following error : 

2023/02/10 14:11:45 ERROR - neoload.Engine: Custom action error, error while executing custom action java.lang.NoClassDefFoundError: com/neotys/rest/dataexchange/client/DataExchangeAPIClientFactory
	at com.neotys.appdynamics.AppDynamicsActionEngine.execute(AppDynamicsActionEngine.java:117)
	at com.neotys.nl.lg.engine.L.internalExecute(L.java:96)
	at com.neotys.nl.lg.engine.m.b(m.java:150)
	at com.neotys.nl.lg.engine.w.d(w.java:122)
	at com.neotys.nl.lg.engine.x.internalExecute(x.java:81)
	at com.neotys.nl.lg.engine.m.b(m.java:150)
	at com.neotys.nl.lg.engine.I.E(I.java:236)
	at com.neotys.nl.lg.engine.I.internalExecute(I.java:94)
	at com.neotys.nl.lg.engine.m.b(m.java:150)
	at com.neotys.nl.lg.engine.d.b(d.java:175)
	at com.neotys.nl.lg.engine.d.run(d.java:106)
Caused by: java.lang.ClassNotFoundException: com.neotys.rest.dataexchange.client.DataExchangeAPIClientFactory
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at com.neotys.nl.common.l.findClass(l.java:114)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at com.neotys.nl.common.l.loadClass(l.java:133)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 11 more

**Comment by stephanemartin** [comment]
Yes that is a know bug fixed in 9.0.3. 
Best regards
